name: "Node.js CI"
description: "A reusable workflow for Node.js projects"

inputs:
  node-version:
    description: "The version of Node.js to use"
    required: false
    default: "18"

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "18"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - run: npm ci
      - run: npm test
